/// Auto-generated by Akythera Labs. 2026. All Rights Reserved.
///
/// Do not modify the source code directly – We highly encourage to use
/// Akythera Labs "File > Export > As Source Code" since your manual changes
/// will always be overwritten by the action.
///
/// A handwritten-style EntityPatchScript compiled from the "epicfight" project's
/// node graphs. The three event flows – onConstruct / onJoinWorld / update – are
/// generated from the Event Graph, and componentsToAttach() returns the attached
/// components as runtime ComponentBlueprints.
///
/// Register entity patch provider with this script by `ComponentsFactory#registerEntityPatchProvider`.
/// Call `new EntityPatch(new PlayerPatchScript(), owner)` to execute hardcoded script.

package com.yesman.epicfight.akythera.scripts.entitypatches;

// Import section is empty. Use auto import feature in IDE

import com.yesman.akythera.api.asset.armature.ArmatureManager;
import com.yesman.akythera.api.world.patch.entity.EntityPatch;
import com.yesman.akythera.core.asset.armature.Armature;
import com.yesman.akythera.core.blueprint.ArmatureComponentBlueprint;
import com.yesman.akythera.core.blueprint.ComponentBlueprint;
import com.yesman.akythera.core.blueprint.script.EntityPatchScript;
import com.yesman.akythera.core.registry.AkytheraRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.level.Level;


import java.util.Map;

public final class PlayerPatchScript implements EntityPatchScript {
    /// The patched entity this script drives (the node graphs' `self` / owner).
    private final EntityPatch<Entity> owner;

    public PlayerPatchScript(final EntityPatch<Entity> owner) {
        this.owner = owner;
    }

    @Override
    public void onConstruct() {
    }

    @Override
    public void onJoinWorld(final Level level) {
    }

    @Override
    public void update() {
    }

    @Override
    public Map<String, ComponentBlueprint<?, ?>> componentsToAttach() {
        return Map.of(
            "armature", new ArmatureComponentBlueprint(ArmatureManager.accessor("epicfight", "humanoid", Armature::new), new ArmatureComponentBlueprint.ByDataPack(ResourceKey.create(AkytheraRegistries.DataPack.ANIMATOR_SCRIPT_KEY, Identifier.parse("epicfight:player"))), true)
        );
    }
}
