/// Auto-generated by Akythera Labs. 2026. All Rights Reserved.
///
/// Do not modify the source code directly – We highly encourage to use
/// Akythera Labs "File > Export > As Source Code" since your manual changes
/// will always be overwritten by the action.
///
/// Wire the provider through each mod loader's datagen register process.
///
/// NeoForge
/// ```
/// private void gatherDataEvent(final GatherDataEvent.Client event) {
///     event.createProvider(EpicfightBlendSpace2Ds::new);
/// }
/// ```
///
/// Fabric
/// ```
/// public final class ExampleModFabricDataGen implements DataGeneratorEntrypoint {
///    @Override
///    public void onInitializeDataGenerator(FabricDataGenerator fabricDataGenerator) {
///        FabricDataGenerator.Pack pack = fabricDataGenerator.createPack();
///        pack.addProvider((FabricDataGenerator.Pack.RegistryDependentFactory<<@NonNull BlendSpace2DProvider>>) EpicfightBlendSpace2Ds::new);
///    }
/// }
/// ```
/// then in your fabric.mod.json,
///
/// ```
/// "entrypoints": {
///   ...
///   "fabric-datagen": [
///     {
///       "value": "com.example.examplemod.ExampleModFabricDataGen"
///     }
///   ],
///   ...
/// },
/// ```

package com.yesman.epicfight.akythera.providers;

// Import section is empty. Use auto import feature in IDE

import com.yesman.akythera.api.data.provider.BlendSpace2DProvider;
import com.yesman.akythera.core.animation.playable.AnimationSequence;
import com.yesman.akythera.core.animation.playable.BlendSpace2D;
import com.yesman.akythera.core.registry.AkytheraRegistries;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;

import java.util.concurrent.CompletableFuture;
import java.util.function.BiConsumer;

public final class EpicfightBlendSpace2Ds extends BlendSpace2DProvider {
    static ResourceKey<BlendSpace2D> createId(final String name) {
        return ResourceKey.create(AkytheraRegistries.DataPack.BLEND_SPACE_2D_KEY, Identifier.fromNamespaceAndPath("epicfight", name));
    }

    public static final ResourceKey<BlendSpace2D> WALK_RUN = createId("walk_run");

    private final CompletableFuture<HolderLookup.Provider> lookupProvider;

    public EpicfightBlendSpace2Ds(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(packOutput);

        this.lookupProvider = lookupProvider;
    }

    @Override
    protected void buildBlendSpace2Ds(BiConsumer<ResourceKey<BlendSpace2D>, BlendSpace2D> writer) {
        HolderLookup.RegistryLookup<AnimationSequence> animSequenceLookup = lookupProvider.join().lookupOrThrow(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY);

        writer.accept(
            WALK_RUN,
            BlendSpace2D
                .builder()
                    .fadeInTime(0.25F).fadeOutTime(0.25F)
                    .smoothX(0.0F).smoothY(0.0F)
                    .minX(-180.0F).maxX(180.0F).minY(0.0F).maxY(4.317181F)
                    .loops(true)
                    .putNode(0.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(45.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(90.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(135.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(180.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(-45.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(-90.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(-135.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(-180.0F, 0.0F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/idle"))))
                    .putNode(0.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_forward"))))
                    .putNode(-45.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_forward_left"))))
                    .putNode(45.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_forward_right"))))
                    .putNode(-90.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_left"))))
                    .putNode(90.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_right"))))
                    .putNode(180.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_backward"))))
                    .putNode(-180.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_backward"))))
                    .putNode(-135.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_backward_left"))))
                    .putNode(135.0F, 4.317181F, animSequenceLookup.getOrThrow(ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.parse("epicfight:humanoid/walk_backward_right"))))
                .create()
        );
    }
}
