/// Auto-generated by Akythera Labs. 2026. All Rights Reserved.
///
/// Do not modify the source code directly – We highly encourage to use
/// Akythera Labs "File > Export > As Source Code" since your manual changes
/// will always be overwritten by the action.
///
/// Wire the provider through each mod loader's datagen register process.
///
/// NeoForge
/// ```
/// private void gatherDataEvent(final GatherDataEvent.Client event) {
///     event.createProvider(EpicfightItemPatches::new);
/// }
/// ```
///
/// Fabric
/// ```
/// public final class ExampleModFabricDataGen implements DataGeneratorEntrypoint {
///    @Override
///    public void onInitializeDataGenerator(FabricDataGenerator fabricDataGenerator) {
///        FabricDataGenerator.Pack pack = fabricDataGenerator.createPack();
///        pack.addProvider((FabricDataGenerator.Pack.RegistryDependentFactory<@NonNull ItemPatchBlueprintProvider>) EpicfightItemPatches::new);
///    }
/// }
/// ```
/// then in your fabric.mod.json,
///
/// ```
/// "entrypoints": {
///   ...
///   "fabric-datagen": [
///     {
///       "value": "com.example.examplemod.ExampleModFabricDataGen"
///     }
///   ],
///   ...
/// },
/// ```

package com.yesman.epicfight.akythera.providers;

// Import section is empty. Use auto import feature in IDE

import com.yesman.akythera.api.data.provider.ItemPatchBlueprintProvider;
import com.yesman.akythera.core.blueprint.ItemPatchBlueprint;
import com.yesman.akythera.core.registry.AkytheraRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;

import java.util.Map;
import java.util.Optional;
import java.util.function.BiConsumer;

public final class EpicfightItemPatches extends ItemPatchBlueprintProvider {
    static ResourceKey<ItemPatchBlueprint> createId(final String name) {
        return ResourceKey.create(AkytheraRegistries.DataPack.ITEM_PATCH_KEY, Identifier.fromNamespaceAndPath("epicfight", name));
    }

    public static final ResourceKey<ItemPatchBlueprint> MINECRAFT_DIAMOND_SWORD = createId("minecraft/diamond_sword");

    public EpicfightItemPatches(PackOutput packOutput) {
        super(packOutput);
    }

    @Override
    protected void buildItemPatches(BiConsumer<ResourceKey<ItemPatchBlueprint>, ItemPatchBlueprint> writer) {
        writer.accept(
            MINECRAFT_DIAMOND_SWORD,
            new ItemPatchBlueprint(
                Optional.empty(),
                Map.of()
            )
        );
    }
}
