/// Auto-generated by Akythera Labs. 2026. All Rights Reserved.
///
/// Do not modify the source code directly – We highly encourage to use
/// Akythera Labs "File > Export > As Source Code" since your manual changes
/// will always be overwritten by the action.
///
/// Emits the entity patch blueprints as datapack JSON at datagen — the *data-driven* distribution
/// path (the engine executes the flows through DataDrivenEntityPatchScript). For a handwritten-style
/// script class instead, see the exported scripts/entitypatches/*PatchScript.java sources.
///
/// Wire the provider through each mod loader's datagen register process.
///
/// NeoForge
/// ```
/// private void gatherDataEvent(final GatherDataEvent.Client event) {
///     event.createProvider(EpicfightEntityPatches::new);
/// }
/// ```
///
/// Fabric
/// ```
/// public final class ExampleModFabricDataGen implements DataGeneratorEntrypoint {
///    @Override
///    public void onInitializeDataGenerator(FabricDataGenerator fabricDataGenerator) {
///        FabricDataGenerator.Pack pack = fabricDataGenerator.createPack();
///        pack.addProvider((FabricDataGenerator.Pack.RegistryDependentFactory<@NonNull EntityPatchBlueprintProvider>) EpicfightEntityPatches::new);
///    }
/// }
/// ```
/// then in your fabric.mod.json,
///
/// ```
/// "entrypoints": {
///   ...
///   "fabric-datagen": [
///     {
///       "value": "com.example.examplemod.ExampleModFabricDataGen"
///     }
///   ],
///   ...
/// },
/// ```

package com.yesman.epicfight.akythera.providers;

// Import section is empty. Use auto import feature in IDE

import com.yesman.akythera.api.asset.armature.ArmatureManager;
import com.yesman.akythera.api.data.modularize.node.SequenceNode;
import com.yesman.akythera.api.data.provider.EntityPatchBlueprintProvider;
import com.yesman.akythera.core.asset.armature.Armature;
import com.yesman.akythera.core.blueprint.ArmatureComponentBlueprint;
import com.yesman.akythera.core.blueprint.EntityPatchBlueprint;
import com.yesman.akythera.core.registry.AkytheraRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;

import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;

public final class EpicfightEntityPatches extends EntityPatchBlueprintProvider {
    static ResourceKey<EntityPatchBlueprint> createId(final String name) {
        return ResourceKey.create(AkytheraRegistries.DataPack.ENTITY_PATCH_KEY, Identifier.fromNamespaceAndPath("epicfight", name));
    }

    public static final ResourceKey<EntityPatchBlueprint> MINECRAFT_PLAYER = createId("minecraft/player");

    public EpicfightEntityPatches(PackOutput packOutput) {
        super(packOutput);
    }

    @Override
    protected void buildScripts(BiConsumer<ResourceKey<EntityPatchBlueprint>, EntityPatchBlueprint> writer) {
        writer.accept(
            MINECRAFT_PLAYER,
            new EntityPatchBlueprint(
                Map.of(
                    "armature", new ArmatureComponentBlueprint(ArmatureManager.accessor("epicfight", "humanoid", Armature::new), new ArmatureComponentBlueprint.ByDataPack(ResourceKey.create(AkytheraRegistries.DataPack.ANIMATOR_SCRIPT_KEY, Identifier.parse("epicfight:player"))), true)
                ),
                AkytheraRegistries.Frozen.SCRIPT_FUNCTION.getValue(Identifier.parse("akythera:player_patch_ctor")),
                new SequenceNode(
                    List.of()
                ),
                new SequenceNode(
                    List.of()
                ),
                new SequenceNode(
                    List.of()
                ),
                List.of()
            )
        );
    }
}
