/// Auto-generated by Akythera Labs. 2026. All Rights Reserved.
///
/// Do not modify the source code directly – We highly encourage to use
/// Akythera Labs "File > Export > As Source Code" since your manual changes
/// will always be overwritten by the action.
///
/// Wire the provider through each mod loader's datagen register process.
///
/// NeoForge
/// ```
/// private void gatherDataEvent(final GatherDataEvent.Client event) {
///     event.createDatapackRegistryObjects(
///         new RegistrySetBuilder().add(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, EpicfightAnimationSequences::bootstrap)
///     );
///
///     event.createProvider(EpicfightAnimationSequences::new);
/// }
/// ```
///
/// Fabric
/// ```
/// public final class ExampleModFabricDataGen implements DataGeneratorEntrypoint {
///    @Override
///    public void buildRegistry(RegistrySetBuilder registryBuilder) {
///        registryBuilder.add(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, EpicfightAnimationSequences::bootstrap);
///    }
///
///    @Override
///    public void onInitializeDataGenerator(FabricDataGenerator fabricDataGenerator) {
///        FabricDataGenerator.Pack pack = fabricDataGenerator.createPack();
///        pack.addProvider((FabricDataGenerator.Pack.RegistryDependentFactory<@NonNull AnimationSequenceProvider>) EpicfightAnimationSequences::new);
///    }
/// }
/// ```
/// then in your fabric.mod.json,
///
/// ```
/// "entrypoints": {
///   ...
///   "fabric-datagen": [
///     {
///       "value": "com.example.examplemod.ExampleModFabricDataGen"
///     }
///   ],
///   ...
/// },
/// ```

package com.yesman.epicfight.akythera.providers;

// Import section is empty. Use auto import feature in IDE

import com.yesman.akythera.api.animation.notify.impl.LogNotify;
import com.yesman.akythera.api.animation.notify.impl.LogNotifyState;
import com.yesman.akythera.api.asset.animation.AnimationManager;
import com.yesman.akythera.api.data.provider.AnimationSequenceProvider;
import com.yesman.akythera.core.animation.notify.AnimationNotifyTrack;
import com.yesman.akythera.core.animation.playable.AnimationSequence;
import com.yesman.akythera.core.math.TimeWindow;
import com.yesman.akythera.core.registry.AkytheraRegistries;
import com.yesman.akythera.core.util.LogicalSide;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.function.BiConsumer;

public final class EpicfightAnimationSequences extends AnimationSequenceProvider {
    static ResourceKey<AnimationSequence> createId(final String name) {
        return ResourceKey.create(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY, Identifier.fromNamespaceAndPath("epicfight", name));
    }

    public static final ResourceKey<AnimationSequence> HUMANOID_IDLE = createId("humanoid/idle");
    public static final ResourceKey<AnimationSequence> HUMANOID_IDLE_AIR = createId("humanoid/idle_air");
    public static final ResourceKey<AnimationSequence> HUMANOID_IDLE_WATER = createId("humanoid/idle_water");
    public static final ResourceKey<AnimationSequence> HUMANOID_RUN_FORWARD = createId("humanoid/run_forward");
    public static final ResourceKey<AnimationSequence> HUMANOID_WALK_BACKWARD = createId("humanoid/walk_backward");
    public static final ResourceKey<AnimationSequence> HUMANOID_WALK_BACKWARD_LEFT = createId("humanoid/walk_backward_left");
    public static final ResourceKey<AnimationSequence> HUMANOID_WALK_BACKWARD_RIGHT = createId("humanoid/walk_backward_right");
    public static final ResourceKey<AnimationSequence> HUMANOID_WALK_FORWARD = createId("humanoid/walk_forward");
    public static final ResourceKey<AnimationSequence> HUMANOID_WALK_FORWARD_LEFT = createId("humanoid/walk_forward_left");
    public static final ResourceKey<AnimationSequence> HUMANOID_WALK_FORWARD_RIGHT = createId("humanoid/walk_forward_right");
    public static final ResourceKey<AnimationSequence> HUMANOID_WALK_LEFT = createId("humanoid/walk_left");
    public static final ResourceKey<AnimationSequence> HUMANOID_WALK_RIGHT = createId("humanoid/walk_right");

    public static void bootstrap(BootstrapContext<AnimationSequence> context) {
        context.register(
            HUMANOID_IDLE,
            new AnimationSequence(
                new AnimationNotifyTrack(
                    List.of(
                        new AnimationNotifyTrack.NotifyInTimeStamp(new LogNotify(LogicalSide.CLIENT), 30.82192F)
                    ),
                    List.of(
                        new AnimationNotifyTrack.NotifyStateInTimeWindow(new LogNotifyState(LogicalSide.SERVER), TimeWindow.create(81.1233F, 102.7233F))
                    )
                ),
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/idle")),
                0.25F,
                0.25F,
                true,
                false
            )
        );
        context.register(
            HUMANOID_IDLE_AIR,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/idle_air")),
                0.25F,
                0.25F,
                true,
                false
            )
        );
        context.register(
            HUMANOID_IDLE_WATER,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/idle_water")),
                0.25F,
                0.25F,
                true,
                false
            )
        );
        context.register(
            HUMANOID_RUN_FORWARD,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/run_forward")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
        context.register(
            HUMANOID_WALK_BACKWARD,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/walk_backward")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
        context.register(
            HUMANOID_WALK_BACKWARD_LEFT,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/walk_backward_left")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
        context.register(
            HUMANOID_WALK_BACKWARD_RIGHT,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/walk_backward_right")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
        context.register(
            HUMANOID_WALK_FORWARD,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/walk_forward")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
        context.register(
            HUMANOID_WALK_FORWARD_LEFT,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/walk_forward_left")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
        context.register(
            HUMANOID_WALK_FORWARD_RIGHT,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/walk_forward_right")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
        context.register(
            HUMANOID_WALK_LEFT,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/walk_left")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
        context.register(
            HUMANOID_WALK_RIGHT,
            new AnimationSequence(
                AnimationNotifyTrack.EMPTY,
                AnimationManager.accessor(Identifier.parse("epicfight:humanoid/locomotion/walk_right")),
                0.25F,
                0.25F,
                false,
                false
            )
        );
    }

    private final CompletableFuture<HolderLookup.Provider> lookupProvider;

    public EpicfightAnimationSequences(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(packOutput);
        this.lookupProvider = lookupProvider;
    }

    @Override
    protected void buildAnimSequences(BiConsumer<ResourceKey<AnimationSequence>, AnimationSequence> writer) {
        HolderLookup.RegistryLookup<AnimationSequence> registryLookup = lookupProvider.join().lookupOrThrow(AkytheraRegistries.DataPack.ANIM_SEQUENCE_KEY);

        writer.accept(HUMANOID_IDLE, registryLookup.getOrThrow(HUMANOID_IDLE).value());
        writer.accept(HUMANOID_IDLE_AIR, registryLookup.getOrThrow(HUMANOID_IDLE_AIR).value());
        writer.accept(HUMANOID_IDLE_WATER, registryLookup.getOrThrow(HUMANOID_IDLE_WATER).value());
        writer.accept(HUMANOID_RUN_FORWARD, registryLookup.getOrThrow(HUMANOID_RUN_FORWARD).value());
        writer.accept(HUMANOID_WALK_BACKWARD, registryLookup.getOrThrow(HUMANOID_WALK_BACKWARD).value());
        writer.accept(HUMANOID_WALK_BACKWARD_LEFT, registryLookup.getOrThrow(HUMANOID_WALK_BACKWARD_LEFT).value());
        writer.accept(HUMANOID_WALK_BACKWARD_RIGHT, registryLookup.getOrThrow(HUMANOID_WALK_BACKWARD_RIGHT).value());
        writer.accept(HUMANOID_WALK_FORWARD, registryLookup.getOrThrow(HUMANOID_WALK_FORWARD).value());
        writer.accept(HUMANOID_WALK_FORWARD_LEFT, registryLookup.getOrThrow(HUMANOID_WALK_FORWARD_LEFT).value());
        writer.accept(HUMANOID_WALK_FORWARD_RIGHT, registryLookup.getOrThrow(HUMANOID_WALK_FORWARD_RIGHT).value());
        writer.accept(HUMANOID_WALK_LEFT, registryLookup.getOrThrow(HUMANOID_WALK_LEFT).value());
        writer.accept(HUMANOID_WALK_RIGHT, registryLookup.getOrThrow(HUMANOID_WALK_RIGHT).value());
    }
}