/// Auto-generated by Akythera Labs. 2026. All Rights Reserved.
///
/// Do not modify the source code directly – We highly encourage to use
/// Akythera Labs "File > Export > As Source Code" since your manual changes
/// will always be overwritten by the action.
///
/// A handwritten-style AnimatorScript compiled from the "epicfight" project's
/// node graphs. Register it through your mod's ComponentsFactory / entity
/// patch wiring wherever a DataDrivenAnimatorScript would otherwise be used.
///
/// Register this script to `AkytheraRegistries.Frozen.SCRIPT_TYPE` to expose
/// the script class to AkytheraLabs, listing your animator scripts in
/// entity patch script > armature patchComponent

package com.yesman.epicfight.akythera.scripts.animator;

// Import section is empty. Use auto import feature in IDE

import com.yesman.akythera.api.animation.animator.AnimationLayer;
import com.yesman.akythera.core.animation.animator.BlendingAnimator;
import com.yesman.akythera.core.animation.driver.AnimationDriver;
import com.yesman.akythera.core.animation.driver.AnimationLayerSignature;
import com.yesman.akythera.core.animation.driver.AnimationStateMachine;
import com.yesman.akythera.core.animation.driver.CachedPoseReference;
import com.yesman.akythera.core.animation.keyframe.Pose;
import com.yesman.akythera.core.blueprint.script.AnimatorScript;
import com.yesman.akythera.core.reflection.ScriptField;
import com.yesman.akythera.core.util.helper.MathUtils;
import com.yesman.akythera.core.util.helper.VectorUtils;
import net.minecraft.resources.Identifier;
import net.minecraft.world.phys.Vec3;

import java.util.Map;

public final class PlayerAnimatorScript implements AnimatorScript {
    @ScriptField
    private double speed = 0.0D;

    @ScriptField
    private float moveYRot = 0.0F;

    @ScriptField
    private boolean isMoving = false;

    @ScriptField
    private Vec3 lastPosition = new Vec3(0.0, 0.0, 0.0);

    /// The script owner, captured at construct time (the node graphs' `self`).
    private BlendingAnimator animator;

    @Override
    public void construct(final Map<AnimationLayerSignature, AnimationLayer> animLayerMap, final Map<String, AnimationDriver> poseCaches, final BlendingAnimator animator) {
        this.animator = animator;
        lastPosition = this.animator.getOwner().position();
        animLayerMap.put(AnimationLayerSignature.ENUM_MANAGER.getOrThrow(Identifier.parse("akythera:base")), AnimationLayer.create(new CachedPoseReference("Locomotion", this.animator)));
        poseCaches.put("Locomotion", new AnimationStateMachine<>(
    this.animator.getOwner(),
    AnimationStateMachine.stateModelBuilder()
));
    }

    @Override
    public void update(final float frameTime, final float partialTick) {
        var cse_6_0 = this.animator.getOwner().getPosition(partialTick);
        var cse_7_0 = cse_6_0.subtract(lastPosition);
        speed = (cse_7_0.length() * (1.0D / frameTime));
        lastPosition = cse_6_0;
        isMoving = (speed > 0.05D);
        var cse_20_0 = this.animator.getOwner();
        moveYRot = (float) (VectorUtils.getAngleBetween(cse_7_0, cse_20_0.calculateViewVector(0.0F, cse_20_0.getYRot(partialTick)), MathUtils.YP, 3));
    }

    @Override
    public Pose getFinalPose(final Map<AnimationLayerSignature, AnimationLayer> layers) {
        return layers.get(AnimationLayerSignature.ENUM_MANAGER.getOrThrow(Identifier.parse("akythera:base"))).getPose();
    }
}
