/// Auto-generated by Akythera Labs. 2026. All Rights Reserved.
///
/// Do not modify the source code directly – We highly encourage to use
/// Akythera Labs "File > Export > As Source Code" since your manual changes
/// will always be overwritten by the action.
///
/// Register this enum class while your mod is constructed, before the manager loads its enums.
/// The namespace of every constant's identifier is the mod id passed here, so pass "epicfight" to
/// keep the identifiers the project authored.
///
/// NeoForge
/// ```
/// @Mod(ExampleMod.MODID)
/// public class ExampleModNeoForged {
///     public ExampleModNeoForged(IEventBus modEventBus, ModContainer modContainer) {
///         FSMAnimationState.ENUM_MANAGER.registerEnumCls("epicfight", EpicfightFSMAnimationState.class);
///     }
/// }
/// ```
///
/// Fabric
/// ```
/// public final class ExampleModDataBlockInitializer implements EnumerableDataBlockInitializer {
///     @Override
///     public void registerEnums() {
///         FSMAnimationState.ENUM_MANAGER.registerEnumCls("epicfight", EpicfightFSMAnimationState.class);
///     }
/// }
/// ```
/// then in your fabric.mod.json,
///
/// ```
/// "entrypoints": {
///   ...
///   "enumerable_data_block_initializer": [
///     {
///       "value": "com.example.examplemod.ExampleModDataBlockInitializer"
///     }
///   ],
///   ...
/// },
/// ```
///
/// `FSMAnimationState.ENUM_MANAGER.loadEnum()` is called by the mod that declares the manager. Call it yourself
/// only when that mod is yours.

package com.yesman.epicfight.akythera.datablocks;

// Import section is empty. Use auto import feature in IDE

import com.yesman.akythera.core.animation.FSMAnimationState;

public enum EpicfightFSMAnimationState implements FSMAnimationState {
    CROUCH("crouch"),
    CROUCH_WALK("crouch_walk"),
    FALL("fall"),
    FLY("fly"),
    IDLE("idle"),
    IN_WATER("in_water"),
    JUMP("jump"),
    LAND("land"),
    MOVE("move"),
    ON_AIR("on_air"),
    ON_GROUND("on_ground"),
    SWIM("swim");

    final int id;

    EpicfightFSMAnimationState(final String identifierPath) {
        this.id = FSMAnimationState.ENUM_MANAGER.assign(this, identifierPath);
    }

    @Override
    public int universalOrdinal() {
        return this.id;
    }
}
