#version 460 core

layout(local_size_x = 128) in;

// Dynamic Input Buffer
layout(std430, binding = 0) readonly buffer PoseBuffer {
    mat4 poses[];
};

// Static Buffer
layout(std430, binding = 1) readonly buffer VertexBuffer {
    struct {
        vec3 position;
        vec3 normal;
        ivec2 joints; // 骨骼&权重在池子中的范围
        //ivec2 weights; //  from weights[w.x] to weights[w.y]
    } vertices[];
};

layout(std430, binding = 2) readonly buffer JointsPool {
    int joints[];
};

layout(std430, binding = 3) readonly buffer WeightsPool {
    float weights[];
};


// Output Buffer
layout(std430, binding = 4) writeonly buffer OutputPositionBuffer {
    vec3 out_pos[];
};

layout(std430, binding = 5) writeonly buffer OutputNormalBuffer {
    uint out_normal[];
};

layout(std430, binding = 6) writeonly buffer OutputColorBuffer {
    vec4 out_color[];
};

layout(std430, binding = 7) writeonly buffer OutputUV1Buffer {
    uint out_uv1[];
};

layout(std430, binding = 8) writeonly buffer OutputUV2Buffer {
    uint out_uv2[];
};

layout(location=0) uniform vec4 colorIn;
layout(location=1) uniform uint uv1In;
layout(location=2) uniform uint uv2In;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= vertices.length()) return; // 边界检查

    vec3 pos = vertices[idx].position;
    vec3 norm = vertices[idx].normal;
    ivec2 joints = vertices[idx].joints;

    vec4 finalPos = vec4(0);
    vec3 finalNormal = vec3(0);

    for (int i = joints.x; i < joints.y; ++i) {
        if (weights[i] > 0.0) {

            // 坐标
            mat4 boneMat = poses[joints[i]];
            finalPos += weights[i] * (boneMat * vec4(pos, 1.0));

            // 法线
            mat3 normalMat = transpose(inverse(mat3(boneMat)));
            finalNormal += weights[i] * (normalMat * norm);
        }
    }

    out_pos[idx] = finalPos.xyz;
    out_normal[idx] = packSnorm4x8(vec4(normalize(finalNormal), 0.0));
    out_color[idx] = colorIn;
    out_uv1[idx] = uv1In;
    out_uv2[idx] = uv2In;
}