#version 460 core

layout(local_size_x = 128) in;

// Dynamic Input Buffer
layout(std430, binding = 0) readonly buffer PoseBuffer {
    mat4 poses[];
};

// Static Buffer
layout(std430, binding = 1) readonly buffer VertexBuffer {
    struct {
        float px,py,pz,nx,ny,nz;
        int jts,jte; // 骨骼&权重在池子中的范围
        //ivec2 weights; //  from weights[w.x] to weights[w.y]
    } vertices[];
};

layout(std430, binding = 2) readonly buffer JointsPool {
    int joints[];
};

layout(std430, binding = 3) readonly buffer WeightsPool {
    float weights[];
};


// Output Buffer
layout(std430, binding = 4) writeonly buffer OutputPositionBuffer {
    float out_pos[];
};

layout(std430, binding = 5) writeonly buffer OutputNormalBuffer {
    uint out_normal[];
};

layout(std430, binding = 6) writeonly buffer OutputColorBuffer {
    vec4 out_color[];
};

layout(std430, binding = 7) writeonly buffer OutputUV1Buffer {
    uint out_uv1[];
};

layout(std430, binding = 8) writeonly buffer OutputUV2Buffer {
    uint out_uv2[];
};

layout(location=0) uniform vec4 colorIn;
layout(location=1) uniform uint uv1In;
layout(location=2) uniform uint uv2In;
layout(location=3) uniform mat4 modelView;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= vertices.length()) return; // check.

    vec4 pos = vec4(vertices[idx].px, vertices[idx].py, vertices[idx].pz, 1.0);
    vec4 norm = vec4(vertices[idx].nx, vertices[idx].ny, vertices[idx].nz, 0.0);

    vec4 finalPos = vec4(0);
    vec4 finalNormal = vec4(0);

    for (int i = jt.x; i < jt.y; ++i) {
        if (weights[i] > 0.0) {
            mat4 boneMat = poses[joints[i]];

            finalPos += (boneMat * pos) * weights[i];
            finalNormal += boneMat * norm * weights[i];
        }
    }

    //finalPos = modelView * finalPos;
    //finalNormal = mat3(modelView) * finalNormal;
    out_pos[idx * 3] = finalPos.x;
    out_pos[idx * 3 + 1] = finalPos.y;
    out_pos[idx * 3 + 2] = finalPos.z;

    out_normal[idx] = packSnorm4x8(vec4(normalize(finalNormal.xyz), 0.0));

    out_color[idx] = colorIn;
    out_uv1[idx] = uv1In;
    out_uv2[idx] = uv2In;
}